# Generated by Django 3.0.8 on 2020-08-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('m_type', models.EmailField(max_length=100)),
                ('price', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.EmailField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.Membership')),
            ],
        ),
    ]
