# Generated by Django 3.0.8 on 2020-08-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20200813_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='coupon',
            name='mesoge',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
