# Generated by Django 3.0.8 on 2020-08-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20200813_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='mesoge',
            new_name='message',
        ),
    ]
