# Generated by Django 3.0.8 on 2020-08-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_auto_20200813_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='message',
            new_name='mesoge',
        ),
    ]
