# Generated by Django 3.0.8 on 2020-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_auto_20200813_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='mesoge',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
