# Generated by Django 3.0.8 on 2020-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0011_auto_20200813_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(max_length=100)),
            ],
        ),
    ]
