# Generated by Django 3.0.8 on 2020-08-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0014_coupon_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='expire_date',
            new_name='expiry_date',
        ),
    ]
