# Generated by Django 3.0.8 on 2020-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0015_auto_20200821_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
