# Generated by Django 3.0.8 on 2020-08-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0016_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
