# Generated by Django 3.0.8 on 2020-08-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0018_auto_20200822_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
    ]
