# Generated by Django 3.0.8 on 2020-08-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0019_remove_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
