# Generated by Django 3.0.8 on 2020-08-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0020_coupon_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='email',
        ),
    ]
