# Generated by Django 3.0.8 on 2020-08-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0021_remove_coupon_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
