# Generated by Django 3.0.8 on 2020-08-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0023_coupon_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon_Detail',
        ),
    ]
