# Generated by Django 3.0.8 on 2020-08-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0024_delete_coupon_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
