# Generated by Django 3.0.8 on 2020-08-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0025_coupon_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.Coupon')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.Membership')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
