# Generated by Django 3.0.8 on 2020-08-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0026_auto_20200827_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='m_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.Company'),
        ),
        migrations.AddField(
            model_name='membership',
            name='currency_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='max_companies',
            field=models.IntegerField(null=True),
        ),
    ]
