# Generated by Django 3.0.8 on 2020-08-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0028_auto_20200827_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='coupons.Currency'),
        ),
    ]
