# Generated by Django 3.0.8 on 2020-08-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0029_membership_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='coupons.Company'),
        ),
    ]
