# Generated by Django 3.0.8 on 2020-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0030_coupon_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
