# Generated by Django 3.0.8 on 2020-08-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0034_auto_20200830_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
