# Generated by Django 3.0.8 on 2020-08-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0035_auto_20200830_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
